package:
  name: q2-annotate
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - altair
  - beautifulsoup4
  - bracken
  - busco >=5.5.0
  - diamond
  - eggnog-mapper >=2.1.10
  - gfatools
  - kaiju
  - kraken2
  - metabat2
  - pandas
  - parameterized
  - qiime2 {{ qiime2_epoch }}.*
  - q2-types {{ qiime2_epoch }}.*
  - q2templates {{ qiime2_epoch }}.*
  - q2-assembly {{ qiime2_epoch }}.*
  - q2-quality-control {{ qiime2_epoch }}.*
  - samtools
  - seqtk
  - tqdm
  - xmltodict
  - pyhmmer
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - parameterized
  imports:
  - q2_annotate
  - qiime2.plugins.annotate
  commands:
  - pytest --pyargs q2_annotate
about:
  home: https://github.com/bokulich-lab/q2-annotate
  license: BSD-3-Clause
  license_family: BSD
